AdHoc (setup) Fix recursive error while preparing release folder
While running the deployment, it comes to an
RuntimeError: maximum recursion depth exceeded in __instancecheck_
This was caused by following some symlinks. This symlinks should
not be followed. Adding the 'no follow' option helps preventing this
error.

This fix was inspired by
https://github.com/ansible/ansible/issues/39456